# Generated by Django 4.0.1 on 2022-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknotes',
            name='notes',
            field=models.CharField(max_length=200),
        ),
    ]
